version: '3.8'

services:
  web:
    build: ./myecommerce
    command: gunicorn --bind 0.0.0.0:8000 myecommerce.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - media_files:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=myecommerce.settings
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_files:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_files:












# version: '3.8'

# services:
#   web:
#     build: ./myecommerce
#     command: gunicorn --bind 0.0.0.0:8000 myecommerce.wsgi:application
#     volumes:
#       # - .:/app
#       # - static_volume:/usr/share/nginx/html/static/
#       - static_volume:/django/staticfiles
#       - media_files:/django/media
#       # - media_volume:/usr/share/nginx/html/media/
#     environment:
#       - DJANGO_SETTINGS_MODULE:myecommerce.settings
#     ports:
#       - "8000:8000"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       # - static_volume:/usr/share/nginx/html/static/
#       # - media_files:/usr/share/nginx/html/media/
#       - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf:ro
#       - static_volume:/var/www/static
#       - media_files:/var/www/media
#     depends_on:
#       - web

# volumes:
#   static_volume:
#   media_files:












# version: '3.8'

# services:
#   web:
#     build: ./myecommerce
#     command: gunicorn --bind 0.0.0.0:8000 myecommerce.wsgi:application
#     volumes:
#       - .:/app
#       - static_volume:/usr/share/nginx/html/static/
#       - media_volume:/usr/share/nginx/html/media/
#     environment:
#       - DJANGO_SETTINGS_MODULE=myecommerce.settings
#     expose:
#       - "8000"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - static_volume:/usr/share/nginx/html/static/
#       - media_volume:/usr/share/nginx/html/media/
#       - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf

# volumes:
#   static_volume:
#   media_volume:














# # version: '3.8'

# services:
#   backend:
#     build:
#       context: ./myecommerce
#       # dockerfile: Dockerfile.backend
#     # command: sh /django/entrypoint.sh
#     volumes:
#       - static_volume:/django/staticfiles
#       - media_files:/django/media
#     environment:
#       DJANGO_SETTINGS_MODULE: myecommerce.settings
#     ports:
#       - "8000:8000"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:8080"
#     volumes:
#       # - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf
#       - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
#       - static_volume:/var/www/static
#       - media_files:/var/www/media
#     depends_on:
#       - backend

# volumes:
#   static_volume:
#   media_files:
